[2025-01-04T13:57:15.816+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.ft_balance_f manual__2025-01-04T13:57:10.039546+00:00 [queued]>
[2025-01-04T13:57:15.831+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.ft_balance_f manual__2025-01-04T13:57:10.039546+00:00 [queued]>
[2025-01-04T13:57:15.832+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-04T13:57:15.849+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): ft_balance_f> on 2025-01-04 13:57:10.039546+00:00
[2025-01-04T13:57:15.856+0000] {standard_task_runner.py:60} INFO - Started process 732 to run task
[2025-01-04T13:57:15.862+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'ft_balance_f', 'manual__2025-01-04T13:57:10.039546+00:00', '--job-id', '1808', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpehnk2mzz']
[2025-01-04T13:57:15.865+0000] {standard_task_runner.py:88} INFO - Job 1808: Subtask ft_balance_f
[2025-01-04T13:57:17.300+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.ft_balance_f manual__2025-01-04T13:57:10.039546+00:00 [running]> on host 8e43a3616b86
[2025-01-04T13:57:18.043+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abershits' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='ft_balance_f' AIRFLOW_CTX_EXECUTION_DATE='2025-01-04T13:57:10.039546+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-04T13:57:10.039546+00:00'
[2025-01-04T13:57:23.073+0000] {base.py:83} INFO - Using connection ID 'postgres_db' for task execution.
[2025-01-04T13:57:23.209+0000] {base.py:83} INFO - Using connection ID 'postgres_db' for task execution.
[2025-01-04T13:57:23.230+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-04T13:57:23.246+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=ft_balance_f, execution_date=20250104T135710, start_date=20250104T135715, end_date=20250104T135723
[2025-01-04T13:57:23.283+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-04T13:57:23.327+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
