[2025-01-06T09:46:45.521+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.ft_balance_f manual__2025-01-06T09:46:40.712844+00:00 [queued]>
[2025-01-06T09:46:45.536+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.ft_balance_f manual__2025-01-06T09:46:40.712844+00:00 [queued]>
[2025-01-06T09:46:45.536+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-06T09:46:45.574+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): ft_balance_f> on 2025-01-06 09:46:40.712844+00:00
[2025-01-06T09:46:45.585+0000] {standard_task_runner.py:60} INFO - Started process 135 to run task
[2025-01-06T09:46:45.591+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'ft_balance_f', 'manual__2025-01-06T09:46:40.712844+00:00', '--job-id', '1918', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpwx50vjpj']
[2025-01-06T09:46:45.594+0000] {standard_task_runner.py:88} INFO - Job 1918: Subtask ft_balance_f
[2025-01-06T09:46:45.668+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.ft_balance_f manual__2025-01-06T09:46:40.712844+00:00 [running]> on host 7a6df65f772c
[2025-01-06T09:46:45.794+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abershits' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='ft_balance_f' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T09:46:40.712844+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-06T09:46:40.712844+00:00'
[2025-01-06T09:46:50.838+0000] {base.py:83} INFO - Using connection ID 'postgres_db' for task execution.
[2025-01-06T09:46:51.008+0000] {base.py:83} INFO - Using connection ID 'postgres_db' for task execution.
[2025-01-06T09:46:51.029+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-06T09:46:51.040+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=ft_balance_f, execution_date=20250106T094640, start_date=20250106T094645, end_date=20250106T094651
[2025-01-06T09:46:51.100+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-06T09:46:51.128+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
