[2025-01-07T21:09:20.910+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.ft_balance_f manual__2025-01-07T21:09:16.167602+00:00 [queued]>
[2025-01-07T21:09:20.928+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.ft_balance_f manual__2025-01-07T21:09:16.167602+00:00 [queued]>
[2025-01-07T21:09:20.928+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-07T21:09:20.970+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): ft_balance_f> on 2025-01-07 21:09:16.167602+00:00
[2025-01-07T21:09:20.980+0000] {standard_task_runner.py:60} INFO - Started process 102 to run task
[2025-01-07T21:09:20.985+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'ft_balance_f', 'manual__2025-01-07T21:09:16.167602+00:00', '--job-id', '1932', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmp4nt7ugg_']
[2025-01-07T21:09:20.992+0000] {standard_task_runner.py:88} INFO - Job 1932: Subtask ft_balance_f
[2025-01-07T21:09:21.075+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.ft_balance_f manual__2025-01-07T21:09:16.167602+00:00 [running]> on host 870f083ddbad
[2025-01-07T21:09:21.224+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abershits' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='ft_balance_f' AIRFLOW_CTX_EXECUTION_DATE='2025-01-07T21:09:16.167602+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-07T21:09:16.167602+00:00'
[2025-01-07T21:09:28.671+0000] {base.py:83} INFO - Using connection ID 'postgres_db' for task execution.
[2025-01-07T21:09:38.381+0000] {base.py:83} INFO - Using connection ID 'postgres_db' for task execution.
[2025-01-07T21:09:38.488+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-07T21:09:38.520+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=ft_balance_f, execution_date=20250107T210916, start_date=20250107T210920, end_date=20250107T210938
[2025-01-07T21:09:38.577+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-07T21:09:38.630+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
