[2025-01-04T14:13:23.164+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.md_account_d manual__2025-01-04T14:13:18.145789+00:00 [queued]>
[2025-01-04T14:13:23.187+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.md_account_d manual__2025-01-04T14:13:18.145789+00:00 [queued]>
[2025-01-04T14:13:23.188+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-04T14:13:23.259+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): md_account_d> on 2025-01-04 14:13:18.145789+00:00
[2025-01-04T14:13:23.269+0000] {standard_task_runner.py:60} INFO - Started process 150 to run task
[2025-01-04T14:13:23.274+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'md_account_d', 'manual__2025-01-04T14:13:18.145789+00:00', '--job-id', '1819', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpzd7s3lc1']
[2025-01-04T14:13:23.279+0000] {standard_task_runner.py:88} INFO - Job 1819: Subtask md_account_d
[2025-01-04T14:13:24.226+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.md_account_d manual__2025-01-04T14:13:18.145789+00:00 [running]> on host 11306dadb3f6
[2025-01-04T14:13:24.312+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abershits' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='md_account_d' AIRFLOW_CTX_EXECUTION_DATE='2025-01-04T14:13:18.145789+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-04T14:13:18.145789+00:00'
[2025-01-04T14:13:29.358+0000] {base.py:83} INFO - Using connection ID 'postgres_db' for task execution.
[2025-01-04T14:13:29.528+0000] {base.py:83} INFO - Using connection ID 'postgres_db' for task execution.
[2025-01-04T14:13:29.548+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-04T14:13:29.561+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=md_account_d, execution_date=20250104T141318, start_date=20250104T141323, end_date=20250104T141329
[2025-01-04T14:13:29.603+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-04T14:13:29.628+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
