[2025-01-04T13:58:33.784+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.ft_balance_f manual__2025-01-04T13:58:30.710049+00:00 [queued]>
[2025-01-04T13:58:33.796+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.ft_balance_f manual__2025-01-04T13:58:30.710049+00:00 [queued]>
[2025-01-04T13:58:33.796+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-04T13:58:33.813+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): ft_balance_f> on 2025-01-04 13:58:30.710049+00:00
[2025-01-04T13:58:33.822+0000] {standard_task_runner.py:60} INFO - Started process 774 to run task
[2025-01-04T13:58:33.825+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'ft_balance_f', 'manual__2025-01-04T13:58:30.710049+00:00', '--job-id', '1813', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpi1580xhw']
[2025-01-04T13:58:33.828+0000] {standard_task_runner.py:88} INFO - Job 1813: Subtask ft_balance_f
[2025-01-04T13:58:34.205+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.ft_balance_f manual__2025-01-04T13:58:30.710049+00:00 [running]> on host 8e43a3616b86
[2025-01-04T13:58:34.843+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abershits' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='ft_balance_f' AIRFLOW_CTX_EXECUTION_DATE='2025-01-04T13:58:30.710049+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-04T13:58:30.710049+00:00'
[2025-01-04T13:58:45.246+0000] {base.py:83} INFO - Using connection ID 'postgres_db' for task execution.
[2025-01-04T13:58:50.682+0000] {base.py:83} INFO - Using connection ID 'postgres_db' for task execution.
[2025-01-04T13:58:50.718+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-04T13:58:50.738+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=ft_balance_f, execution_date=20250104T135830, start_date=20250104T135833, end_date=20250104T135850
[2025-01-04T13:58:50.817+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-04T13:58:50.865+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
