[2025-01-04T15:32:13.437+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.md_account_d manual__2025-01-04T15:21:18.190378+00:00 [queued]>
[2025-01-04T15:32:13.450+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.md_account_d manual__2025-01-04T15:21:18.190378+00:00 [queued]>
[2025-01-04T15:32:13.451+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2025-01-04T15:32:13.468+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): md_account_d> on 2025-01-04 15:21:18.190378+00:00
[2025-01-04T15:32:13.477+0000] {standard_task_runner.py:60} INFO - Started process 187 to run task
[2025-01-04T15:32:13.482+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'md_account_d', 'manual__2025-01-04T15:21:18.190378+00:00', '--job-id', '1875', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmppsg4lr9u']
[2025-01-04T15:32:13.484+0000] {standard_task_runner.py:88} INFO - Job 1875: Subtask md_account_d
[2025-01-04T15:32:13.723+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.md_account_d manual__2025-01-04T15:21:18.190378+00:00 [running]> on host 00bb408c4f3b
[2025-01-04T15:32:13.806+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abershits' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='md_account_d' AIRFLOW_CTX_EXECUTION_DATE='2025-01-04T15:21:18.190378+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-04T15:21:18.190378+00:00'
[2025-01-04T15:32:18.743+0000] {base.py:83} INFO - Using connection ID 'postgres_db' for task execution.
[2025-01-04T15:32:18.913+0000] {base.py:83} INFO - Using connection ID 'postgres_db' for task execution.
[2025-01-04T15:32:18.933+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-04T15:32:18.945+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=md_account_d, execution_date=20250104T152118, start_date=20250104T153213, end_date=20250104T153218
[2025-01-04T15:32:18.997+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-04T15:32:19.022+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
