[2025-01-04T17:25:18.178+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.md_account_d manual__2025-01-04T17:25:12.607812+00:00 [queued]>
[2025-01-04T17:25:18.207+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.md_account_d manual__2025-01-04T17:25:12.607812+00:00 [queued]>
[2025-01-04T17:25:18.209+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-04T17:25:18.245+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): md_account_d> on 2025-01-04 17:25:12.607812+00:00
[2025-01-04T17:25:18.260+0000] {standard_task_runner.py:60} INFO - Started process 261 to run task
[2025-01-04T17:25:18.266+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'md_account_d', 'manual__2025-01-04T17:25:12.607812+00:00', '--job-id', '1905', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpadit7lxu']
[2025-01-04T17:25:18.271+0000] {standard_task_runner.py:88} INFO - Job 1905: Subtask md_account_d
[2025-01-04T17:25:19.152+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.md_account_d manual__2025-01-04T17:25:12.607812+00:00 [running]> on host ef69f4633403
[2025-01-04T17:25:19.294+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abershits' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='md_account_d' AIRFLOW_CTX_EXECUTION_DATE='2025-01-04T17:25:12.607812+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-04T17:25:12.607812+00:00'
[2025-01-04T17:25:24.361+0000] {base.py:83} INFO - Using connection ID 'postgres_db' for task execution.
[2025-01-04T17:25:24.578+0000] {base.py:83} INFO - Using connection ID 'postgres_db' for task execution.
[2025-01-04T17:25:24.604+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-04T17:25:24.626+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=md_account_d, execution_date=20250104T172512, start_date=20250104T172518, end_date=20250104T172524
[2025-01-04T17:25:24.694+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-04T17:25:24.739+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
